export default {
  light: {
    primary: "#5D7AFF",
    primaryLight: "#E4E9FF",
    primaryDark: "#3D5CFF",
    secondary: "#FFB17A",
    secondaryLight: "#FFE9D9",
    background: "#FFFFFF",
    card: "#F8F9FA",
    cardHover: "#F0F2F5",
    text: "#1A1A1A",
    textSecondary: "#4A4A4A",
    subtext: "#6E7A8A",
    border: "#E5E7EB",
    borderLight: "#F0F2F5",
    success: "#4CAF50",
    successLight: "#E8F5E9",
    error: "#F44336",
    errorLight: "#FFEBEE",
    warning: "#FFC107",
    warningLight: "#FFF8E1",
    info: "#2196F3",
    infoLight: "#E3F2FD",
    shadow: "rgba(0, 0, 0, 0.08)",
    overlay: "rgba(0, 0, 0, 0.5)",
  },
};